
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BD2_demaOkien.Data
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Visit
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Visit()
    {

        this.LAB_examination = new HashSet<LAB_examination>();

        this.Physical_examination = new HashSet<Physical_examination>();

    }


    public int visit_id { get; set; }

    public string description { get; set; }

    public string diagnosis { get; set; }

    public string status { get; set; }

    public Nullable<System.DateTime> registration_date { get; set; }

    public Nullable<System.DateTime> ending_date { get; set; }

    public int patient_id { get; set; }

    public int doctor_id { get; set; }

    public int registerer_id { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LAB_examination> LAB_examination { get; set; }

    public virtual Patient Patient { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Physical_examination> Physical_examination { get; set; }

        public virtual Worker Worker { get; set; }

        public virtual Worker Worker1 { get; set; }

    }

}
