//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD2_demaOkien.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.Visit = new HashSet<Visit>();
            this.Visit1 = new HashSet<Visit>();
        }
    
        public int Worker_id { get; set; }
        public string Role { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public Nullable<int> NPWZ { get; set; }
        public string E_mail_Address { get; set; }
        public int Phone_number { get; set; }
        public int PESEL { get; set; }
        public int address_id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit> Visit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit> Visit1 { get; set; }
    }
}
